# Generated by Django 5.1.3 on 2024-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], default='small', max_length=6),
        ),
        migrations.AddField(
            model_name='service',
            name='price_big',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_medium',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_small',
            field=models.BigIntegerField(default=0),
        ),
    ]
